source 'https://rubygems.org'

gem 'httparty', '~> 0.21'
gem 'ipaddress', '~> 0.8.3'
gem 'json', '~> 2.6'
gem 'logger', '~> 1.5'
gem 'resolv', '~> 0.2.2'
gem 'rufus-scheduler', '~> 3.8'
gem 'sqlite3', '~> 1.6'
gem 'websocket-client-simple', '~> 0.6.1'
